### ISSUE TITLE
This plugin not support 1.20.1?

### ISSUE THREAD

**Issue by xinhaihai** [ACM02/XpBank#2]
My core is PurPur frequently reports errors during use
[09:08:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'xpbank' in plugin XpBank v1.12.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1017) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2392) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2352) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1452) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Experience progress must be between 0.0 and 1.0 (-1524.0)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.setExp(CraftPlayer.java:1718) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at me.head_block.xpbank.commands.Xp.addXp(Xp.java:551) ~[XPBank.jar:?]
	at me.head_block.xpbank.commands.Xp.asPlayer(Xp.java:182) ~[XPBank.jar:?]
	at me.head_block.xpbank.commands.Xp.onCommand(Xp.java:49) ~[XPBank.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 23 more

**Comment by ACM02** [comment]
Hello xinhaihai, I'm sorry you have been encountering these issues with my plugin. I have just done some testing in version 1.20.1 and the plugin seems to work fine for me. The error you are encountering seems to be a bug in the math used to calculate the experience points and would affect the plugin on all Minecraft versions, I will do my best to see if I can figure out what caused this and publish a bug fix as soon as I can.
